### ISSUE TITLE
Лагает под WINE

### ISSUE THREAD

**Issue by wipedlifepotato** [NeedForKillTheGame/needforkill.ru#12]
Дико лагает под WINE

Всё что пишет - ../src/intel/isl/isl.c:2235: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.

**Comment by pgbv** [comment]
Рекомендую попробовать отключить CSMT.
Для этого нужно открыть `wine regedit`, зайти в `HKEY_CURRENT_USER → Software → Wine → Direct3D` и поменять `csmt` на `0`.

Изменение данной настройки может отрицательно повлиять на другие игры, возможно лучше завести отдельный профиль.
