### ISSUE TITLE
Удалить ненужные файлы из репозитория

### ISSUE THREAD

**Issue by pgbv** [NeedForKillTheGame/needforkill.ru#5]
После генерации сайта в gohugo от темплейта осталась куча лишних дублированных файлов, которые можно смело удалить

**Comment by pgbv** [comment]
Done

**Comment by nurupo** [comment]
Небольшая заметка: хоть они и удалены, эти файлы все-равно сохранены в гит истории, так что каждый скачивающий этот репозиторий будет так же скачивать эти файлы, он просто не показаны, но можно вернуться назад до их удаления и они будут на месте. В гит можно удалить файлы из истории, это сделает так что ты их изначально не добавлял, но это изменит гит историю - изменит уже существующие коммиты и их хэш коды, так что все скачавшие этот репозиторий будут должны заново его cкачать.

**Comment by pgbv** [comment]
Это понятно, тут дело не в истории, а в том, что сайт был сгенерирован → сайт был отредактирован и запушен, никто не разбирался, какие файлы там на самом деле нужны, а какие нет. Скрывать нечего, надо было просто навести порядок, чтобы было понятней в будущем.
