### ISSUE TITLE
Разобраться с отображением сайта при сужении экрана

### ISSUE THREAD

**Issue by pgbv** [NeedForKillTheGame/needforkill.ru#6]
Вначале при сужении уезжает кнопка проигрывания видео:
![nfksitew1](https://user-images.githubusercontent.com/48351741/79429919-d7e11900-7fd0-11ea-9579-0f314ebf0cad.png)
При совсем узком (мобильном) варианте, не хватает отступа между видео и заголовком.
![nfksitew2](https://user-images.githubusercontent.com/48351741/79429948-e2031780-7fd0-11ea-8bcc-fffa549b80e1.png)

**Comment by zavsievich** [comment]
Привет!
Пофиксил эти ошибки, но не понимаю, как протестить: в html-файлах путь до style.min.css  неправильный, а также никуда не подключены файлы из папки plugins
на гитхабе и на сервере разный код?

**Comment by pgbv** [comment]
Добрый день!
Сайт работает через github pages, т.е. весь актуальный код тут.
По поводу файлов из plugins — тут дело, скорее всего, в https://github.com/NeedForKillTheGame/needforkill.ru/issues/5

**Comment by zavsievich** [comment]
Разобрался, файлы из папки plugins подключены, style.min.css тоже, просто точка входа на сервере и в локальных файлах разная
В этом случае всё отработает как надо

**Comment by pgbv** [comment]
Благодарю, теперь отлично сужается!
